services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ecommerce
    volumes:
      - mongo-data:/data/db

  inventory-service:
    build:
      context: ./inventory-service
    container_name: inventory-service
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongo:27017

  order-service:
    build:
      context: ./order-service
    container_name: order-service
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      - MONGO_URI=mongodb://mongo:27017

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    depends_on:
      - inventory-service
      - order-service
    ports:
      - "8088:8088"

volumes:
  mongo-data: